## R programming Assignment 2: Caching the mean of a vector

## the following function will create a special matrix object
## that can cache its inverse
makeCacheMatrix <- function(x = matrix()) {
	inv <- NULL
	set <- function (y) {
		x <<- y
		inv <<- NULL
}

get <- function ()x
setinverse <- function (inverse) inv <<- inverse
getinverse <- function () inv
list (set=set, get=get, setinverse=setinverse, getinverse=getinverse)
} 



## the following function will compute the invers of the special matrix 
## generated by the previous function. 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
}

#The following function gives the inverse of the matrix. It checks to see if #inverse has already been computed and if so gets the results. 
# This function assumes that the matrix is always invertible.
cacheSolve <- function(x, ...) {
    inv <- x$getinverse()
    if(!is.null(inv)) {
        message("getting cached data.")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$setinverse(inv)
    inv
}
